#------------------------------------------------------------------------------
# ktune configuration file for sim2real system identification
#
# Testbed: Pendulum setup â€” see `Syssid_Testbed_Setup.xlsx` for physical parameters.
# Purpose: Used with ktune to drive and record trajectory for system identification.
#
# Notes for users:
#   - Units are SI (meters, kilograms, seconds, newtons, radians)
#---------------------------#---------------------------
# Testbed: Pendulum (see Pendulum_Testbed_Configurations.xlsx for details)
# Mass in kg
# Inertia in kg*m^2
# Length in meters
# Configuration
    # Disc_B 
    # Axle_A
    # Spacer_Set2 (B,C,D)
    # Arm_B (150mm)
#---------------------------
sysid:
  # Hardware configuration
  actuator_id: 11
  motor_name: "sts3215v12"
  ip: "192.168.42.1"

  # Pendulum Params
  total_inertia: 0.013687744
  total_g_bias: -0.82361664
  length: 0.150
  mass: 0.535
  
  # Motor parameters
  error_gain: 0.16489
  winding_resistance: 1.0
  torque_constant: 1.0787
  
  # Test configuration
  repetitions: 4
  kp_values: [4, 8, 12, 16, 24, 32]
  trajectories: 
    - "lift_and_drop"
    - "sin_sin"
    - "up_and_down"
    - "sin_time_square"
    - "brutal"

 
